version: "3"

services:
  cache-api:
    build: .
    restart: always
    command: npm start
    env_file:
      - .env
    volumes:
      - './:/poupa-up'
    ports:
      - '3000:3000'
    depends_on:
      - database
    networks:
      - cache-api-network

  database:
    image: mongo
    container_name: 'database'
    env_file:
      - .env
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017:27017'
    networks:
      - cache-api-network

networks:
  cache-api-network:
    driver: bridge