version: "3"

services:
  cache-api:
    build: .
    restart: always
    container_name: 'cache-api'
    env_file:
      - .env
    volumes:
      - './:/app'
      - ./nodemon.json:/home/node/app/nodemon.json
    ports:
      - '3000:3000'
    depends_on:
      - database
    networks:
      - cache-api-network
    command: npm run dev

  database:
    image: mongo
    container_name: 'database'
    environment:
      - MONGO_COLLECTION_NAME=dummy
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017:27017'
    networks:
      - cache-api-network

networks:
  cache-api-network:
    driver: bridge